### ISSUE TITLE
Support for self-hosted ntfy instances

### ISSUE THREAD

**Issue by amotl** [vict0rsch/ntfy-wrapper#8]
Dear Victor,

thanks a stack for conceiving and maintaining this excellent package.

Over at [mqttwarn](https://github.com/jpmens/mqttwarn), we used to use [Apprise](https://github.com/caronc/apprise) to submit notifications to [ntfy](https://ntfy.sh/), which worked great. However, because we wanted to have better control within mqttwarn, we are adding a dedicated mqttwarn ntfy adapter now, see [mqttwarn ntfy adapter documentation](https://mqttwarn.readthedocs.io/en/latest/notifier-catalog.html#ntfy).

We had a look at your `ntfy-wrapper` package, but have not been able to use it right away, because it currently does not support [self-hosted ntfy instances](https://docs.ntfy.sh/install/).

https://github.com/vict0rsch/ntfy-wrapper/blob/8d5e28c0ba747a660e058e43954e807eeccb1450/ntfy_wrapper/notifier.py#L406-L410

We think it would be so sweet if `ntfy-wrapper` could gain a feature to be able to define the ntfy HTTP API **baseurl** in some elegant way, in order to make using the library on self-hosted instances a first-citizen use case.

With kind regards,
Andreas.

/cc @binwiederhier

#### References
- https://github.com/jpmens/mqttwarn/pull/610
- https://github.com/jpmens/mqttwarn/pull/638

**Comment by vict0rsch** [comment]
@amotl can you checkout #9 and tell me if that works for you?

**Comment by amotl** [comment]
Thank you very much. I've validated the improvement on behalf of GH-10. It works well.

**Comment by vict0rsch** [comment]
Merged #9 #10 and released `0.1.7`
